HF_TOKEN: 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
KAGGLE_API_TOKEN: KGAT_30844e52b5f439c7de54181670ea006d
BUCKET: kaggle

SSH_USER: "notebook"
SSH_PASSWORD : "notebook123" 
SSH_HOST : "127.0.0.1"
SSH_PORT : 2222

TUNNELMATE_BROKER : "https://165.99.219.95"
BROKER_HOST : "165.99.219.95"
BROKER_CONTROL_PORT : 7000
SCOPE : "open"                              
PROTOCOL : "tcp"
