ID: stabilize
TITLE: "stabilize"
HF_TOKEN: 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
KAGGLE_API_TOKEN: KGAT_8dd27d0ca5eee0cd8112876b206455fb
DEST_BUCKET: DRINF_stabilized
BOT_TOKEN: "8821793448:AAEwdlfh3gjJ7lSalyopWTjLHrvONitMetw"
CHAT_ID: "5962517274"
CRF: 12
VIDEO: "https://huggingface.co/datasets/hamimmahmud0/DRINF/resolve/main/Nadirs/Bakshi%20bazaar/1%20Aug%2C%202026/DJI_0103.MP4"