ID: stabilize
TITLE: "stabilize"
HF_TOKEN: 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
KAGGLE_API_TOKEN: ""
SOURCE_BUCKET: hamimmahmud0/CVAT_frame_extraction/DJI_0266_merged
DEST_BUCKET: SAM_COCO_v1
CONFIDENCE: 0.25
BATCH_SIZE: 8
BOT_TOKEN: ""
BOTUSER: "@Hamim_mahmud"


PROMPTS:
  - Pedestrian
  - Vehicle
  - Car
  - Bus
  - Truck
  - Motorcycle
  - Bicycle
  - Rickshaw

